### ISSUE TITLE
Don't hardcode "python" as default executable

### ISSUE THREAD

**Issue by tuhdo** [syohex/emacs-helm-pydoc#8]
On [this line](https://github.com/syohex/emacs-helm-pydoc/blob/master/helm-pydoc.el#L51), `python` is being set as default executable. I think it should use `python-shell-interpreter` variable, since the default value is also `python`. The reason is that on Windows, I have to explicitly set `python-shell-interpreter` to a path to be able to execute `M-x run-python`, but `helm-pydoc` still couldn't see my Python executable. I had to fix the function to reuse the variable to make `helm-pydoc` work on Windows.

**Comment by syohex** [comment]
Thanks for reporting. I fixed at #9. Please check latest version.
